name: gen_example
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  gen_annotation:
    git:
      url: https://github.com/Order-of-Runes/gen_annotation.git
      ref: 0.0.2
  json_annotation: ^4.9.0
  rusty_dart:
    git:
      url: https://github.com/TheMakersPrime/rusty_dart.git
      ref: main

dev_dependencies:
  build_runner: ^2.4.14
  gen:
    path: ../
  json_serializable: ^6.9.3
  very_good_analysis: ^7.0.0