name: gen
description: "An opinionated code generator"
version: 0.0.12
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ^7.4.1
  build: ^2.4.2
  build_resolvers: ^2.4.3
  dart_style: ^3.0.1
  gen_annotation:
    git:
      url: https://github.com/Order-of-Runes/gen_annotation.git
      ref: 0.0.2
  json_annotation: ^4.9.0
  pub_semver: ^2.1.5
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0

dependency_overrides:
  analyzer: 7.3.0