targets:
  $default:
    builders:
      gen|view_model_generator:
        enabled: true
        generate_for:
          - lib/features/**/*view_model.dart
          - lib/core/src/theme_switcher/*view_model.dart
          - lib/core/src/bithub/bithub.dart

      gen|model_generator:
        enabled: true
        generate_for:
          - lib/features/**/*model.dart

      json_serializable:
        enabled: true
        generate_for:
          - lib/model/models.dart
        options:
          checked: true
